### ISSUE TITLE
The deepest level of a nested list fails to render the text in a paragraph

### ISSUE THREAD

**Issue by owjsub** [faelys/libsoldout#37]
With this Markdown snippet in libsoldout, the deepest level does not render the text in paragraphs. Observe the correct behavior at http://daringfireball.net/projects/markdown/dingus.

```
1. Lorem ipsum dolor sit amet

2. Consectetur adipiscing elit

3. Aliquam congue tincidunt purus

    1. Eget feugiat elit finibus eleifend

        1. Duis id

        2. Scelerisque vel non mauris

    2. Donec consectetur libero metus

4. Ac pulvinar magna semper eleifend
```

The issue may be related to the following snippet in  `markdown.c->parse_listitem`

```
while (end < size && data[end - 1] != '\n') end += 1;
if (is_empty(data + beg, end - beg)) {
  in_empty = 1;
  beg = end;
  continue; }
```

**Comment by faelys** [comment]
I do agree that there is a bug here, I will look into it.

I already had a quick look but I did not find any obvious culprit. Would you mind sharing what makes you think the quoted snipped is related to the issue?

Thanks for your report.

**Comment by owjsub** [comment]
The quoted snippet affects the `MKD_LI_BLOCK` flag. The problematic sublist items are rendered inline instead of in a block.

**Comment by faelys** [comment]
So the TL;DR here is that the issue is fixed and you were half-right in pointing out the quoted snippet, that put me in the right tracks.

The purpose of the quoted snippet is to discard the blank lines between list items, so that recursive calls only operate on nicely trimmed text fragments (that is a general principle in this library, it helps the designing and it provides helpful determinism for debugging).

However, this is an online algorithm (so the code is easier to design and maintain), so when encountering a blank line, we can't look ahead to know whether it's a blank line between items or inside an item. For the same reason, once the end of item is reached, we can't backtrack to discard the final blank lines.

So instead, the quoted snippet discards _all_ blank lines, and the subsequent `bufputc(work, '\n');` restores the internal blank lines. Between the snippet and the `bufputc` are two `break;` statements, one when the next item is encountered and the other when the end of list in encountered, so that the final blank lines are never restored.

That's why the snippet wasn't an obvious suspect: not being in paragraphs would hint at overeager blank line removal, but then you discard all of them you can't be overeager.

So far, everything works as intended.

However, when a list marker (something like `2.` or `*`) is encountered, the previous blank line (if any) is never restored, even if it's not the beginning of the next item. That was what cause the issue.

Now it turns one that there is one case where it is useful to discard a non-final blank line: that's the blank line between the last paragraph of a list item and the beginning of the sublist (again, to keep nicely trimmed text fragments), so I added a `bufputc` in the other cases.

Thanks for your report and your hints.

**Comment by owjsub** [comment]
Thanks for the fix! It works great 👍
