### ISSUE TITLE
Error building libsoldout with clang

### ISSUE THREAD

**Issue by slacka** [faelys/libsoldout#41]
When I tried to build libsoldout with clang, I got the following error:
`clang: error: argument unused during compilation: '-pie'`

The same error can be found here:
http://clang.debian.net/logs/2016-08-30/libsoldout_1.4-1_unstable_clang.log

**Comment by faelys** [comment]
The error looks quite straightforward: there is a useless `-pie` argument passed to clang, and it should be removed.

The problem is that I'm not the one who put it there.

This project is very small and simple, and the build system I propose is as small and simple. You can check the repository, it's a basic makefile without any fancy, no autohell or massive contraptions. And there is no `-pie` in there.

If you check further the log, you can see that the flag have clearly been tampered with, there is no `-fdebug-prefix-map` or `-fstack-protector-strong` in my build system either, and certainly not twice on the same command-line.

Also it might be worthwhile to note that unlike what the issue title insinuate, it's not a matter of clang, as I'm using libsoldout compiled while clang, as do AFAIK all users of libsoldout from official FreeBSD binary packages.

It's rather a matter of having the build environment using a value for `LDFLAGS` which is consistent with the compiler.

I'm all for helping make the build easier for downstream in any way I can, but I feel a bit powerless to fix flags that have been overridden from the default values I suggest.

Maybe if someone with a better knowledge of your build system or of Debian's chimed in?

**Comment by markand** [comment]
The problem is up to debian packagers, its their problem so this issue should just be closed.

**Comment by slacka** [comment]
OK,I verified this version works with clang. Sorry for the noise. I'll pass the information to Debian package manager. Thanks!
