### ISSUE TITLE
Code block header issue

### ISSUE THREAD

**Issue by snshn** [faelys/libsoldout#42]
Hello.
Would like to report a small issue I've encountered using your library.
This block of code is not being correctly rendered in the latest master.
```
` ` `
# jessie-backports, from sid
deb http://ftp.debian.org/debian jessie-backports main
` ` `
```
Using the default renderer.
Here's what I got as an output:
```
<p>` ` `</p>
<h1>jessie-backports, from sid</h1>
<p>deb http://ftp.debian.org/debian jessie-backports main
` ` `</p>
```
Note: had to add spaces in between ticks to make the pre's render here properly.

Thank you.

**Comment by faelys** [comment]
What you describe here is sometimes called "fenced code blocks", because they are "fenced" by a marker before the code and a marker after it, unlike original markdown code blocks that are only indented on every line.

Such a syntax is not part of the original markdown standard, and not part of Discount extensions. I was therefore never considered to be implemented in this project.

I guess the easiest workaround is to pre-process the input text, adding one level of indentation on each line between "fences".

**Comment by snshn** [comment]
Oh, I see.
I will utilize the usual 4-space indentation for those code blocks then.
Thank you for your response.
